### ISSUE TITLE
a problem from sample

### ISSUE THREAD

**Issue by peng666** [qinglew/PCN-PyTorch#1]
Hello, I found that there seems to be something wrong with using sample to get GT with '02691156/5e44d38e88458ab1e1873a3963e0d14' . What's wrong？
Thanks a lot.

**Comment by qinglew** [comment]
Could you please give a more detailed description of the error？Screenshots are better.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: peng666 ***@***.***>
发送时间: Friday, March 19, 2021 11:55:46 AM
收件人: qinglew/PCN-PyTorch ***@***.***>
抄送: Subscribed ***@***.***>
主题: [qinglew/PCN-PyTorch] a problem from sample (#1)


Hello, I found that there seems to be something wrong with using sample to get GT with '02691156/5e44d38e88458ab1e1873a3963e0d14' . What's wrong？
Thanks a lot.

―

**Comment by peng666** [comment]
Thank you for your reply.
This is 02691156 / 5e44d38e88458ab1e1873a3963e0d14 in shapenet.v1

![gt](https://user-images.githubusercontent.com/32197329/111913322-97273500-8aa8-11eb-882c-4a986693013c.png)

This is the result of resampling from the model, gt.pcd
![model](https://user-images.githubusercontent.com/32197329/111913324-98586200-8aa8-11eb-870f-1c5929d69096.png)

**Comment by peng666** [comment]
Thank you for your reply.
This is 02691156 / 5e44d38e88458ab1e1873a3963e0d14 in shapenet.v1
![model](https://user-images.githubusercontent.com/32197329/111913437-09981500-8aa9-11eb-889f-a8eb30445f62.png)

This is the result of resampling from the model, gt.pcd
![gt](https://user-images.githubusercontent.com/32197329/111913435-0866e800-8aa9-11eb-87fe-51b0faf7a061.png)

I found that I had more than one model error. Have you ever encountered such a situation？My code comes from PCN's sample.

**Comment by qinglew** [comment]
I try again with the model you said. I got a good point cloud from the `.obj` file.

![demo](https://github.com/qinglew/Images/blob/master/demo.png)

Here is the content of the file generated:

![demo file](https://github.com/qinglew/Images/blob/master/demo_file.png)

I think you should compile the code in your machine again, and the version of the PCL and VTK should be the same as the information in https://github.com/qinglew/PCN-PyTorch/tree/master/sample. I did this in Ubuntu 18.04 LTS. It seems that you are using Windows OS. I think you should check the generated `.pcd` file whether there is some right content. You also can write code to visualize the `.pcd` file generated to check.

**Comment by peng666** [comment]
Thank you very much. I'll check my environment.
