### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by K11205008** [qinglew/PCN-PyTorch#11]
Dear Sir, 

Can I have the dataset for the car that you made?

Thank you.

Best Regards,
Uddin

**Comment by qinglew** [comment]
I recommend the MVP dataset. Here is the link: https://github.com/paul007pl/MVP_Benchmark/tree/main/completion. It contains partial scans and four different resolution complete point clouds.

**Comment by qinglew** [comment]
We have upload the dataset decompressed from original PCN. Please see the shared link of Google Drive.
