### ISSUE TITLE
Implemetation Help

### ISSUE THREAD

**Issue by LebaAnna** [qinglew/PCN-PyTorch#2]
Can you provide a step by step execution of the PCN Pytorch

**Comment by LebaAnna** [comment]
where is the entire dataset available?
Couldn't find the dataset of the path mentioned in the code

**Comment by qinglew** [comment]
You need to download ShapeNet Core v1 and extract 8 categories from the whole dataset which are .ply file. You need to sample from the surface of the PAD model and generate the partial point clouds using the code I provided. The code are located at `render` and `sample` directores. The dataset generated is very big. So you need to generate by yourself. Or you can reference the official code of the PCN model which provides the Google drive address of the dataset.
