### ISSUE TITLE
some questions about train.py

### ISSUE THREAD

**Issue by Marigod98** [qinglew/PCN-PyTorch#20]
maybe this part should be train_step < 50000? not should be epoch<50000
for epoch in range(1, params.epochs + 1):
        # hyperparameter alpha
        if train_step < 10000:
            alpha = 0.01
        elif train_step < 20000:
            alpha = 0.1
        elif epoch < 50000:
            alpha = 0.5
        else:
            alpha = 1.0

**Comment by qinglew** [comment]
Yes, you are right! I have rectified the code.
