### ISSUE TITLE
Doubt on CD 

### ISSUE THREAD

**Issue by LebaAnna** [qinglew/PCN-PyTorch#5]
Thank you so much for providing your code!
May i ask you one thing, usually the cd is in  scale of 10^(-4) right, here its seems to be in scale of 10^(-3). Is there any scaling done?

**Comment by qinglew** [comment]
CD loss in training process is not necessary to be scaled, while evaluating the model, you can scale with 10^-3 or 10^-4. The code I provide in `evaluation.py` is not scaled.
