### ISSUE TITLE
should be io.read_point_cloud

### ISSUE THREAD

**Issue by davodogster** [qinglew/PCN-PyTorch#6]
Hi Thank you very much for developing a pytorch implementation.
I am just starting to use your repo now.

Firstly, I have noticed this error.
Dataset.py imports * from open3d, so you need to add "io."

![image](https://user-images.githubusercontent.com/46079516/125012377-31de6a80-e0be-11eb-9b9e-28887344e5df.png)

Otherwise:

![image](https://user-images.githubusercontent.com/46079516/125012482-6520f980-e0be-11eb-9819-7bff53a61c66.png)

**Comment by qinglew** [comment]
It depends on the version of open3d you used. What I used is an old version.
